// Generated by CoffeeScript 1.9.3
(function() {
  var ApplicationState, JsonSetting;

  ApplicationState = require('./application_state');

  JsonSetting = (function() {
    function JsonSetting(key) {
      this.key = key;
    }

    JsonSetting.prototype.get = function() {
      return ApplicationState.get(this.key);
    };

    JsonSetting.prototype.set = function(value) {
      return ApplicationState.set(this.key, value);
    };

    JsonSetting.prototype.reset = function() {
      return ApplicationState.reset(this.key);
    };

    return JsonSetting;

  })();

  module.exports = JsonSetting;

}).call(this);
