source 'https://rubygems.org'

group :development, :test do
  gem 'rspec', '~> 3.2.0'
  gem 'capybara', '~> 2.4.4'
  gem 'poltergeist', '~> 1.6.0'
  gem 'scss_lint', '0.38.0'

  # temporary workaround for https://github.com/sickill/rainbow/issues/44
  gem 'rainbow', '2.1.0'
end
