// Generated by CoffeeScript 1.11.1
(function() {
  var AnimatableRegion, Application, Marionette, _, bus,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  _ = require('underscore');

  Marionette = require('backbone.marionette');

  AnimatableRegion = require('./animatable_region');

  bus = require('../lib/bus');

  Application = (function(superClass) {
    extend(Application, superClass);

    function Application() {
      return Application.__super__.constructor.apply(this, arguments);
    }

    Application.prototype.region = '#maji-app';

    Application.prototype.regionClass = AnimatableRegion;

    Application.prototype.initialize = function(opts) {
      if (opts == null) {
        opts = {};
      }
      require('./marionette_renderer').setup();
      require('./cordova_support');
      this.bus = bus;
      _.defaults(opts, {
        showTransitions: true
      });
      return this.getRegion().showTransitions = opts.showTransitions;
    };

    return Application;

  })(Marionette.Application);

  module.exports = Application;

}).call(this);
