// Generated by CoffeeScript 1.9.3
(function() {
  var ApplicationState;

  ApplicationState = (function() {
    function ApplicationState() {}

    ApplicationState.prototype.get = function(key) {
      var item;
      item = localStorage.getItem(key);
      if (item) {
        return JSON.parse(item);
      }
    };

    ApplicationState.prototype.set = function(key, value) {
      return localStorage.setItem(key, JSON.stringify(value));
    };

    return ApplicationState;

  })();

  module.exports = new ApplicationState();

}).call(this);
