// Generated by CoffeeScript 1.9.3
(function() {
  var Wreqr, commands, reqres, vent;

  Wreqr = require('backbone.wreqr');

  commands = new Wreqr.Commands();

  vent = new Wreqr.EventAggregator();

  reqres = new Wreqr.RequestResponse();

  module.exports = {
    commands: commands,
    vent: vent,
    reqres: reqres,
    execute: function() {
      return commands.execute.apply(commands, arguments);
    },
    request: function() {
      return reqres.request.apply(reqres, arguments);
    },
    trigger: function() {
      return vent.trigger.apply(vent, arguments);
    }
  };

}).call(this);
