// Generated by CoffeeScript 1.8.0
(function() {
  var $, bus, initCordova, publishOnBus;

  $ = require('jquery');

  bus = require('./bus');

  publishOnBus = function(e) {
    return bus.trigger("app:" + e.type);
  };

  initCordova = function() {
    var eventName, _i, _len, _ref;
    $(document).on('deviceready', function() {
      return require('./cordova/ios_network_activity').init();
    });
    _ref = ['pause', 'resume', 'backbutton', 'offline', 'online'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      eventName = _ref[_i];
      $(document).on(eventName, function(e) {
        return publishOnBus(e);
      });
    }
    return $(function() {
      return $('body').addClass("platform-" + cordova.platformId);
    });
  };

  if (window.cordova) {
    initCordova();
  }

}).call(this);
