// Generated by CoffeeScript 1.9.3
(function() {
  var $, Radio, initCordova;

  $ = require('jquery');

  Radio = require('backbone.radio');

  initCordova = function() {
    var eventName, i, len, ref;
    $(document).on('deviceready', function() {
      return require('./cordova/ios_network_activity').init();
    });
    ref = ['pause', 'resume', 'backbutton', 'offline', 'online'];
    for (i = 0, len = ref.length; i < len; i++) {
      eventName = ref[i];
      $(document).on(eventName, function(e) {
        return Radio.channel('app').trigger(e.type);
      });
    }
    return $(function() {
      return $('body').addClass("platform-" + cordova.platformId);
    });
  };

  if (window.cordova) {
    initCordova();
  }

}).call(this);
