// Generated by CoffeeScript 1.8.0
(function() {
  var I18n;

  I18n = require('i18n-js');

  I18n.fallbacks = true;

  I18n.autoDetectLocale = function() {
    var language, locale, userLocale;
    userLocale = navigator.userLanguage || navigator.language;
    if (userLocale in I18n.translations) {
      return I18n.locale = userLocale;
    }
    language = userLocale.match(/^[a-z]{2}/i)[0];
    for (locale in I18n.translations) {
      if (locale.match(/^[a-z]{2}/i)[0] === language) {
        return I18n.locale = locale;
      }
    }
    return I18n.locale = I18n.defaultLocale;
  };

  module.exports = I18n;

}).call(this);
