// Generated by CoffeeScript 1.8.0
(function() {
  var I18n, Marionette, templateHelpers;

  Marionette = require('backbone.marionette');

  I18n = require('./i18n');

  templateHelpers = require('./template_helpers');

  module.exports.setup = function() {
    var defaultRender;
    defaultRender = Marionette.Renderer.render;
    return Marionette.Renderer.render = function(template, data) {
      data.t = function() {
        return I18n.t.apply(I18n, arguments);
      };
      data.l = function() {
        return I18n.l.apply(I18n, arguments);
      };
      data.h = templateHelpers;
      return defaultRender(template, data);
    };
  };

}).call(this);
