// Generated by CoffeeScript 1.8.0
(function() {
  var NavigationStack, _;

  _ = require('underscore');

  NavigationStack = (function() {
    function NavigationStack() {
      this.stack = [];
      this._prevRoute = null;
    }

    NavigationStack.prototype.push = function(navigationElement) {
      return this.stack.push(navigationElement);
    };

    NavigationStack.prototype.pop = function() {
      return this._prevRoute = this.stack.pop();
    };

    NavigationStack.prototype.unwind = function(route) {
      var i, item, _i, _ref;
      _ref = this.stack;
      for (i = _i = _ref.length - 1; _i >= 0; i = _i += -1) {
        item = _ref[i];
        if (item.route === route) {
          this._prevRoute = this.stack[i + 1] || this.stack[i];
          this.stack = this.stack.slice(0, +i + 1 || 9e9);
          return this._prevRoute;
        }
      }
    };

    NavigationStack.prototype.clear = function() {
      return this.stack = [];
    };

    NavigationStack.prototype.get = function(index) {
      return this.stack[index];
    };

    NavigationStack.prototype.prevRoute = function() {
      var _ref;
      return (_ref = this._prevRoute) != null ? _ref.route : void 0;
    };

    NavigationStack.prototype.length = function() {
      return this.stack.length;
    };

    NavigationStack.prototype.toString = function() {
      return _.pluck(this.stack, 'route').join(', ');
    };

    return NavigationStack;

  })();

  module.exports = NavigationStack;

}).call(this);
