// Generated by CoffeeScript 1.9.3
(function() {
  var NavigationStack, _;

  _ = require('underscore');

  NavigationStack = (function() {
    function NavigationStack() {
      this.stack = [];
      this._prevRoute = null;
    }

    NavigationStack.prototype.push = function(navigationElement) {
      return this.stack.push(navigationElement);
    };

    NavigationStack.prototype.pop = function() {
      return this._prevRoute = this.stack.pop();
    };

    NavigationStack.prototype.unwind = function(route) {
      var i, item, j, ref;
      ref = this.stack;
      for (i = j = ref.length - 1; j >= 0; i = j += -1) {
        item = ref[i];
        if (item.route === route) {
          this._prevRoute = this.stack[i + 1] || this.stack[i];
          this.stack = this.stack.slice(0, +i + 1 || 9e9);
          return this._prevRoute;
        }
      }
    };

    NavigationStack.prototype.clear = function() {
      return this.stack = [];
    };

    NavigationStack.prototype.get = function(index) {
      return this.stack[index];
    };

    NavigationStack.prototype.prevRoute = function() {
      var ref;
      return (ref = this._prevRoute) != null ? ref.route : void 0;
    };

    NavigationStack.prototype.length = function() {
      return this.stack.length;
    };

    NavigationStack.prototype.toString = function() {
      return _.pluck(this.stack, 'route').join(', ');
    };

    return NavigationStack;

  })();

  module.exports = NavigationStack;

}).call(this);
