// Generated by CoffeeScript 1.8.0
(function() {
  var Marionette, Page,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Marionette = require('backbone.marionette');

  Page = (function(_super) {
    __extends(Page, _super);

    function Page() {
      return Page.__super__.constructor.apply(this, arguments);
    }

    Page.prototype.transition = 'slide';

    Page.prototype.className = 'page';

    return Page;

  })(Marionette.Layout);

  module.exports = Page;

}).call(this);
