#!/usr/bin/env bash
[ -z "$APP_ENV" ] && APP_ENV='production'
export APP_ENV=$APP_ENV
export PATH=$PATH:$(npm bin)
export APP_PATH=$(pwd)

cd $APP_PATH && $(dirname ${BASH_SOURCE[0]})/cordova-exec build "$@"
