#!/usr/bin/env bash
shopt -s dotglob # include hidden files in globs
set -e # fail fast

APP_PACKAGE=$1
APP_NAME=$(echo $1 | perl -pe 's/.*\.//')
APP_PATH="$2"

TMP_DIR=$(mktemp -d 2>/dev/null || mktemp -d -t maji)

pushd $(dirname "${BASH_SOURCE[0]}")/../ >/dev/null 2>&1
  cp -R project_template/* "$TMP_DIR"

  pushd "$TMP_DIR" >/dev/null 2>&1
    perl -pi -e "s/##APP_NAME##/$APP_NAME/" README.md
    perl -pi -e "s/##APP_NAME##/$APP_NAME/" package.json
    perl -pi -e "s/##APP_NAME##/$APP_NAME/" cordova/config.xml
    perl -pi -e "s/##APP_NAME##/$APP_NAME/" src/index.html
    perl -pi -e "s/##APP_PACKAGE##/$APP_PACKAGE/" cordova/config.xml
    perl -pi -e "s/##APP_PACKAGE##/$APP_PACKAGE/" cordova/package.json
    perl -pi -e "s/##APP_PACKAGE##/$APP_PACKAGE/" package.json

    # create needed symlinks, NPM removes them
    (cd cordova/ && ln -s ../dist www)
    (cd bin/ && ln -s ../node_modules/.bin/maji .)

    # npm renames .gitignore to .npmignore
    [ -f .npmignore ] && (mv .npmignore .gitignore || exit 0)
  popd >/dev/null 2>&1
popd >/dev/null 2>&1

mkdir -p "$APP_PATH"

mv "$TMP_DIR"/* "$APP_PATH"
rm -r "$TMP_DIR"

cd "$APP_PATH"
bin/setup
