#!/usr/bin/env bash
APP_PACKAGE=$1
APP_NAME=$(echo $1 | perl -pe 's/.*\.//')

[[ "$2" != */ ]] && APP_DIR="$2/" || APP_DIR="$2"
APP_PATH=$APP_DIR$APP_NAME

TMP_DIR=$(mktemp -d -t maji)

pushd $(dirname "${BASH_SOURCE[0]}")/../ >/dev/null 2>&1
  cp -R project_template/ "$TMP_DIR"

  pushd "$TMP_DIR" >/dev/null 2>&1
    perl -pi -e "s/##APP_NAME##/$APP_NAME/" README.md
    perl -pi -e "s/##APP_NAME##/$APP_NAME/" package.json
    perl -pi -e "s/##APP_NAME##/$APP_NAME/" cordova/config.xml
    perl -pi -e "s/##APP_NAME##/$APP_NAME/" public/index.html
    perl -pi -e "s/##APP_NAME##/$APP_NAME/" app/modules/home/templates/index.hamlc
    perl -pi -e "s/##APP_PACKAGE##/$APP_PACKAGE/" cordova/config.xml

    # create needed symlinks, NPM removes them
    (mkdir -p vendor/styles/maji && cd vendor/styles/maji && \
      ln -s ../../../node_modules/maji/css/maji_screen_transitions.scss screen_transitions.scss)
    (cd cordova/ && ln -s ../dist www)
    (cd bin/ && ln -s ../node_modules/.bin/maji .)

    # npm renames .gitignore to .npmignore
    mv .npmignore .gitignore
  popd >/dev/null 2>&1
popd >/dev/null 2>&1

mkdir -p "$APP_PATH"
mv "$TMP_DIR"/* "$APP_PATH"

cd "$APP_PATH"
bin/setup
