#!/usr/bin/env bash
source "$(dirname ${BASH_SOURCE[0]})/_functions"
PLATFORM=$1

pushd cordova >/dev/null 2>&1
  platform_installed $PLATFORM || cordova platforms add $PLATFORM
  cordova prepare $PLATFORM

popd >/dev/null 2>&1
