// Generated by CoffeeScript 1.8.0
(function() {
  var $;

  $ = require('jquery');

  module.exports = {
    init: function() {
      if (!window.NetworkActivity) {
        return;
      }
      $(document).on('ajaxStart', function() {
        return NetworkActivity.activityStart();
      });
      return $(document).on('ajaxStop', function() {
        return NetworkActivity.activityStop();
      });
    }
  };

}).call(this);
