// Generated by CoffeeScript 1.9.3
(function() {
  var TemplateHelpers, _;

  _ = require('underscore');

  TemplateHelpers = (function() {
    function TemplateHelpers() {}

    TemplateHelpers.prototype.register = function(helpers) {
      return _.extend(this, helpers);
    };

    return TemplateHelpers;

  })();

  module.exports = new TemplateHelpers();

}).call(this);
